### ISSUE TITLE
Compat ACF5

### ISSUE THREAD

**Issue by MaximeCulea** [samjco/ACF-toggle-true-false-switcher-field#1]
Hi, first of all could you explain me what's the difference with https://github.com/samjco/acf-switcher ?
And finally, is this plugin compatible for ACF5 ?
Thx

**Comment by samjco** [comment]
Not for Pro Yet.

One is for single toggle, other is for multi toggling.
I have updated the url name.

**Comment by MaximeCulea** [comment]
ok thx.
Cya
